fastlane_version "2.68.0"

# update_fastlane

default_platform :android

platform :android do
  desc "Naive Network Game Distrubution"
  lane :distribute do

      firebase_app_distribution(
          app: "1:706635797480:android:b4ed7cc76874f4e6f14a5d",
          groups: "beta",
          release_notes_file: "Client/Assets/Resources/Changelog.md",
          apk_path: "Client/Builds/Android/NaiveNetworkGame.apk",
      )

  end
end
